In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import folium
from numpy import nan
from sklearn.model_selection import train_test_split

In [ ]:
# Mount to Drive
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("./drive/MyDrive/dataDefi2.csv", sep=';')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.7,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.6,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.6,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
3,66955,4599,19,52.0,36.358025,0,African American,F,180.0,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
4,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.4,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82537,26716,6791,55,54.0,29.357335,1,Other/Unknown,M,182.8,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Undefined diagnoses,0
82538,10009,33376,174,50.0,23.021962,0,Caucasian,M,180.3,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
82539,8410,110955,62,NaN,19.333766,0,Caucasian,F,165.1,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,1
82540,112003,96590,118,75.0,18.906551,0,Caucasian,M,175.3,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
82541,69087,71222,15,76.0,43.621516,0,Caucasian,M,177.8,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Genitourinary,Renal/Genitourinary,0

In [24]:
df2=df.dropna()
df2=df.dropna(axis=0)

df2

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.70,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
4,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.40,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
7,30959,59793,109,37.0,37.073442,1,Caucasian,F,154.94,Operating Room / Recovery,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82535,76720,17017,32,84.0,20.984657,0,Caucasian,F,165.10,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma,0
82536,92861,16349,194,60.0,43.214025,0,Caucasian,M,185.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
82538,10009,33376,174,50.0,23.021962,0,Caucasian,M,180.30,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
82540,112003,96590,118,75.0,18.906551,0,Caucasian,M,175.30,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
82541,69087,71222,15,76.0,43.621516,0,Caucasian,M,177.80,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Genitourinary,Renal/Genitourinary,0

In [29]:
from pickle import TRUE
df = pd.read_csv('../content/dataDefi2.csv', sep=';')

# Новый раздел

In [30]:
df

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.7,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.6,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.6,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
3,66955,4599,19,52.0,36.358025,0,African American,F,180.0,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
4,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.4,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82537,26716,6791,55,54.0,29.357335,1,Other/Unknown,M,182.8,Operating Room / Recovery,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Undefined diagnoses,0
82538,10009,33376,174,50.0,23.021962,0,Caucasian,M,180.3,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
82539,8410,110955,62,NaN,19.333766,0,Caucasian,F,165.1,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,1
82540,112003,96590,118,75.0,18.906551,0,Caucasian,M,175.3,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
82541,69087,71222,15,76.0,43.621516,0,Caucasian,M,177.8,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Genitourinary,Renal/Genitourinary,0

In [35]:
features, targets = df.loc[:, df.columns != "hospital_death"], df.loc[:, df.columns == "hospital_death"]

df=df.dropna().reset_index(drop=True)

df

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.70,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
3,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.40,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
4,30959,59793,109,37.0,37.073442,1,Caucasian,F,154.94,Operating Room / Recovery,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51268,76720,17017,32,84.0,20.984657,0,Caucasian,F,165.10,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma,0
51269,92861,16349,194,60.0,43.214025,0,Caucasian,M,185.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
51270,10009,33376,174,50.0,23.021962,0,Caucasian,M,180.30,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0
51271,112003,96590,118,75.0,18.906551,0,Caucasian,M,175.30,Floor,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0
51272,69087,71222,15,76.0,43.621516,0,Caucasian,M,177.80,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Genitourinary,Renal/Genitourinary,0

In [38]:
train_features, test_features, train_targets, test_targets = train_test_split(
        features, targets,
        train_size=0.9,
        test_size=0.1,
        random_state=42,
        shuffle = True,
        stratify=targets
    )

In [39]:
print('Dims Train :'+str(train_features.shape))
print('Dims Train target :'+str(train_targets.shape))

Dims Train :(46145, 83)
Dims Train target :(46145, 1)

In [40]:
print('Dims Test :'+str(test_features.shape))
print('Dims Test target :'+str(test_targets.shape))

Dims Test :(5128, 83)
Dims Test target :(5128, 1)