In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import folium
from numpy import nan
from sklearn.model_selection import train_test_split

In [ ]:
# Mount to Drive
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("./drive/MyDrive/dataDefi2.csv", sep=';')

In [11]:
from pickle import TRUE
df = pd.read_csv('../content/dataDefi2.csv', sep=';')

In [28]:
df

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.70,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0.0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0.0
3,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.40,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
4,30959,59793,109,37.0,37.073442,1,Caucasian,F,154.94,Operating Room / Recovery,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47178,60107,101635,18,79.0,24.841260,0,African American,M,182.90,Floor,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,1.0
47179,9420,63083,44,51.0,67.289484,0,Caucasian,M,178.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,0.0
47180,127666,75511,196,57.0,43.558388,0,Caucasian,M,180.30,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
47181,79166,78443,13,84.0,30.121094,0,Other/Unknown,M,160.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal,0.0
47182,64351,68534,100,65.0,27.756928,0,Caucasian,F,154.90,Accident & Emergency,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,Sepsis,Cardiovascular,1.0

In [17]:
df2=df.dropna()
df2=df.dropna(axis=0)

df2

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.70,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0.0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0.0
3,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.40,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
4,30959,59793,109,37.0,37.073442,1,Caucasian,F,154.94,Operating Room / Recovery,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47178,60107,101635,18,79.0,24.841260,0,African American,M,182.90,Floor,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,1.0
47179,9420,63083,44,51.0,67.289484,0,Caucasian,M,178.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,0.0
47180,127666,75511,196,57.0,43.558388,0,Caucasian,M,180.30,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
47181,79166,78443,13,84.0,30.121094,0,Other/Unknown,M,160.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal,0.0
47182,64351,68534,100,65.0,27.756928,0,Caucasian,F,154.90,Accident & Emergency,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,Sepsis,Cardiovascular,1.0

# Новый раздел

In [29]:
features, targets = df.loc[:, df.columns != "hospital_death"], df.loc[:, df.columns == "hospital_death"]

df=df.dropna().reset_index(drop=True)

df

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,icu_admit_source,...,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem,hospital_death
0,113303,63835,185,77.0,26.822874,0,African American,M,172.70,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
1,100799,68271,6,19.0,22.890904,0,Asian,M,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0.0
2,97702,25893,77,49.0,33.855754,0,Caucasian,F,167.60,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic,0.0
3,90681,1541,132,83.0,29.277836,0,Caucasian,F,152.40,Accident & Emergency,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
4,30959,59793,109,37.0,37.073442,1,Caucasian,F,154.94,Operating Room / Recovery,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47178,60107,101635,18,79.0,24.841260,0,African American,M,182.90,Floor,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic,1.0
47179,9420,63083,44,51.0,67.289484,0,Caucasian,M,178.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular,0.0
47180,127666,75511,196,57.0,43.558388,0,Caucasian,M,180.30,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular,0.0
47181,79166,78443,13,84.0,30.121094,0,Other/Unknown,M,160.00,Accident & Emergency,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal,0.0
47182,64351,68534,100,65.0,27.756928,0,Caucasian,F,154.90,Accident & Emergency,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,Sepsis,Cardiovascular,1.0

In [30]:
train_features, test_features, train_targets, test_targets = train_test_split(
        features, targets,
        train_size=0.9,
        test_size=0.1,
        random_state=42,
        shuffle = True,
        stratify=targets
    )

In [31]:
print('Dims Train :'+str(train_features.shape))
print('Dims Train target :'+str(train_targets.shape))

Dims Train :(42464, 83)
Dims Train target :(42464, 1)

In [32]:
print('Dims Test :'+str(test_features.shape))
print('Dims Test target :'+str(test_targets.shape))

Dims Test :(4719, 83)
Dims Test target :(4719, 1)

In [33]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

In [ ]:
#Train the model using the training sets
clf.fit(train_features, train_targets)

In [ ]:
#Predict the response for test dataset
y_pred = clf.predict(test_features)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))